/*
 * Copyright (c)
 * Weyoss <weyoss@outlook.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

import { IQueueParsedParams } from '../queue-manager/index.js';

/**
 * Whether a consumer is currently processing messages from a queue.
 *
 * - `active`: a handler instance is running and its dequeue loop is
 *   consuming messages from the queue.
 *
 * - `stopped`: the handler is configured but not running. This happens
 *   when the queue's operational state is not ACTIVE (PAUSED, STOPPED, or
 *   LOCKED), or when the handler is between start and stop during a state
 *   transition.
 */
export type EConsumerQueueStatus = 'active' | 'stopped';

/**
 * A queue the consumer is handling, together with its current
 * consumption status.
 *
 * Returned by `IConsumer.getQueuesWithStatus()`. The `queue` field is the
 * fully-resolved identity — including the effective consumer group ID for
 * PUB/SUB queues, which may be an ephemeral ID generated by the consumer
 * if the user did not supply one.
 */
export interface IConsumerQueuesWithStatus {
  /**
   * The queue the consumer is (or is configured to be) handling.
   * Includes the effective consumer group ID.
   */
  readonly queue: IQueueParsedParams;

  /**
   * Whether a handler is currently running for this queue.
   */
  readonly status: EConsumerQueueStatus;
}
