/*
 * Copyright (c)
 * Weyoss <weyoss@outlook.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

import { ICallback } from 'redis-smq-common';
import { IMessageTransferable } from '../message/index.js';
import { IQueueParsedParams } from '../queue-manager/index.js';

/**
 * A callback-style message handler.
 *
 * Invoked with the message and a completion callback. The handler must
 * call `cb` exactly once — with no arguments on success, or with an
 * `Error` on failure. Calling `cb` more than once is tolerated (the
 * second call is a no-op) but logs a warning at the consumer level.
 *
 * A synchronous throw from the handler is treated the same as calling
 * `cb(error)`: the message is unacknowledged with
 * `EMessageUnacknowledgementCause.UNACKNOWLEDGED` (or a more specific
 * cause, for errors the consumer recognizes).
 *
 * @example
 * const handler: TConsumerMessageHandlerCallback = (msg, cb) => {
 *   process(msg.getBody(), (err) => cb(err));
 * };
 */
export type TConsumerMessageHandlerCallback = (
  msg: IMessageTransferable,
  cb: ICallback<void>,
) => void;

/**
 * A promise-style message handler.
 *
 * Invoked with the message. The consumer awaits the returned promise:
 * resolution is treated as success, rejection as failure with the
 * rejection value as the error.
 *
 * @example
 * const handler: TConsumerMessageHandlerPromise = async (msg) => {
 *   await process(msg.getBody());
 * };
 */
export type TConsumerMessageHandlerPromise = (
  msg: IMessageTransferable,
) => Promise<void>;

/**
 * A handler function in either supported form.
 *
 * The distinction between the two forms is not enforced at runtime. The
 * consumer calls every function handler with both arguments — the
 * message and a completion callback — and dispatches on the return
 * value: a thenable is awaited, a synchronous throw propagates, a
 * callback invocation settles the attempt. This makes the runtime
 * tolerant of wrappers (mocks, decorators) that do not preserve
 * `Function.length` accurately.
 *
 * The union exists to document the two intended signatures, not to
 * constrain dispatch.
 */
export type TConsumerMessageHandlerFn =
  TConsumerMessageHandlerCallback | TConsumerMessageHandlerPromise;

/**
 * A handler as accepted by `IConsumer.consume()`.
 *
 * Three forms are supported:
 *
 *   - callback function: `(msg, cb) => void`
 *   - promise function: `async (msg) => Promise<void>`
 *   - module path: a string ending in `.js` or `.cjs`, resolved by the
 *     consumer and executed in a worker thread
 *
 * The module-path form isolates a handler in its own thread so that a
 * CPU-bound or blocking handler does not stall the consumer's event
 * loop. The module must default-export a function matching one of the
 * two function forms above.
 *
 * @example
 * // Callback handler
 * const a: TConsumerMessageHandler = (msg, cb) => cb();
 *
 * // Promise handler
 * const b: TConsumerMessageHandler = async (msg) => {
 *   await process(msg.getBody());
 * };
 *
 * // Module path handler
 * const c: TConsumerMessageHandler = './handlers/order-handler.js';
 */
export type TConsumerMessageHandler = string | TConsumerMessageHandlerFn;

/**
 * The parameters a message handler is registered with.
 *
 * This describes "a handler bound to a specific queue" — the shape the
 * consumer's internal registry stores. Users interact with handlers via
 * `IConsumer.consume(queue, handler)`, which constructs one of these
 * internally; it is rare for user code to build one directly.
 *
 * It appears in the public contract because the current public API
 * exports it. Future tightening of the public surface could move it to
 * an internal directory; that would be a breaking change and is not
 * undertaken here.
 *
 * `queue` is intentionally mutable. The consumer's registration path
 * resolves the effective consumer group ID after the parameters are
 * first constructed — for a PUB/SUB queue without an explicit group, it
 * generates an ephemeral ID and reassigns `queue` to include it. Making
 * this field readonly would break that assignment.
 *
 * `messageHandler` is never reassigned. It is the same reference for the
 * lifetime of the registration.
 */
export interface IConsumerMessageHandlerParams {
  /**
   * The queue the handler is registered for.
   *
   * For a PUB/SUB queue, the `groupId` may be replaced during
   * registration with the effective group ID — an explicit one supplied
   * by the caller, or an ephemeral `cid-<consumerId>` generated by the
   * consumer.
   */
  queue: IQueueParsedParams;

  /**
   * The handler itself, in any of the three accepted forms.
   */
  readonly messageHandler: TConsumerMessageHandler;
}
