---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by user.
--- DateTime: 2/20/24 1:12 PM
---

local keyHeartbeats = KEYS[1]
local keyHeartbeatsTimestamps = KEYS[2]

local keyConsumerQueues = ''

local consumerId = ''

local keyIndexOffset = 2
local argvIndexOffset = 0

local function clean()
    redis.call("HDEL", keyHeartbeats, consumerId)
    redis.call("ZREM", keyHeartbeatsTimestamps, consumerId)
    redis.call("DEL", keyConsumerQueues)
end

if #ARGV > argvIndexOffset then
    for index in pairs(ARGV) do
        consumerId = ARGV[index]
        keyConsumerQueues = KEYS[keyIndexOffset + 1]
        keyIndexOffset = keyIndexOffset + 1
        clean()
    end
    return 'OK'
end

return 'INVALID_PARAMETERS'