name: 'Documentation Bug Report'
description: Report an issue or inaccuracy in the RedisSMQ documentation

body:
  - type: markdown
    attributes:
      value: |
        # Documentation Bug Report
        Thank you for taking the time to report a documentation issue. This helps us improve the RedisSMQ documentation for everyone.
        
        ## Guidelines
        - Be specific about what's incorrect or missing
        - Include examples of what you expected to find
        - Suggest improvements if possible

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Clearly describe the issue you found in the documentation.
      placeholder: The documentation is missing information about X, contains incorrect information about Y, or is unclear about Z.
    validations:
      required: true

  - type: input
    id: affected-url
    attributes:
      label: Affected Documentation URL
      description: Link to the specific page or section containing the issue.
      placeholder: https://github.com/weyoss/redis-smq/wiki/...
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Documentation Issue
      description: Select the category that best describes the issue.
      options:
        - Missing information
        - Incorrect information
        - Unclear explanation
        - Outdated content
        - Code example doesn't work
        - Broken link
        - Formatting/display issue
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: documentation-goal
    attributes:
      label: What Were You Looking For?
      description: Describe what information you were trying to find when you encountered this issue.
      placeholder: I was trying to understand how to configure X or implement Y feature...

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: If applicable, list the steps that led you to encounter this issue.
      placeholder: |
        1. Went to page X
        2. Clicked on section Y
        3. Tried to follow instructions for Z
        4. Found that the information was incorrect/missing

  - type: textarea
    id: expected-vs-actual-behavior
    attributes:
      label: Expected vs. Actual Documentation
      description: Describe what you expected to find and what you actually found.
      placeholder: |
        Expected: Clear instructions on how to configure X with examples.
        Actual: The configuration section only mentions X briefly without examples.

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Improvement
      description: If possible, suggest how the documentation could be improved.
      placeholder: Adding a code example showing how to configure X would make this clearer.

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Drag and drop images here to upload them.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other context that might help us understand and address the issue.
      placeholder: Version of RedisSMQ you're using, related issues, etc.

  - type: markdown
    attributes:
      value: |
        ## Thank You!
        Your contribution helps make RedisSMQ documentation better for everyone.
