name: Feature Request 💡
description: Suggest a new feature for RedisSMQ
labels: ['type: feature']
body:
  - type: markdown
    attributes:
      value: |
        These issues are for **concrete and actionable proposals**.

  - type: textarea
    id: user-story
    attributes:
      label: Describe the user story
      description:  |
        A clear and concise description of what workflow is meant to be improved. Example: "As a developer, I often want to do <something>, but I often face <problem>".
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Consider that pnpm is used by many people, and your particular use case might not make sense to implement in the core.
    validations:
      required: true

  - type: textarea
    id: drawbacks
    attributes:
      label: Describe the drawbacks of your solution
      description: This section is important not only to identify future issues, but also for us to see whether you thought through your request. Ask yourself, what are the problems we could have maintaining what you propose? How often will it break?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered, and why you think they wouldn't be good enough.
    validations:
      required: false