/*
 * Copyright (c)
 * Weyoss <weyoss@protonmail.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

// This file is auto-generated from errors.template.ts by scripts/generate-error-mappings.js
// Do not edit this file directly. Edit the template or the generator instead.

/**
 * The generator replaces the placeholder below with entries like:
 * ErrorName: [400, 'ErrorName'],
 */
export const errors = {
  ConfigurationError: [400, 'ConfigurationError'],
  ConfigurationMessageQueueSizeError: [
    400,
    'ConfigurationMessageQueueSizeError',
  ],
  ConfigurationMessageStoreExpireError: [
    400,
    'ConfigurationMessageStoreExpireError',
  ],
  ConfigurationNamespaceError: [400, 'ConfigurationNamespaceError'],
  ConsumerError: [500, 'ConsumerError'],
  ConsumerGroupNotEmptyError: [409, 'ConsumerGroupNotEmptyError'],
  ConsumerGroupNotFoundError: [404, 'ConsumerGroupNotFoundError'],
  ConsumerGroupRequiredError: [400, 'ConsumerGroupRequiredError'],
  ConsumerGroupsError: [500, 'ConsumerGroupsError'],
  ConsumerGroupsNotSupportedError: [501, 'ConsumerGroupsNotSupportedError'],
  ExchangeFanoutError: [500, 'ExchangeFanoutError'],
  ExchangeHasBoundQueuesError: [500, 'ExchangeHasBoundQueuesError'],
  InvalidConsumerGroupIdError: [400, 'InvalidConsumerGroupIdError'],
  InvalidDirectExchangeParametersError: [
    400,
    'InvalidDirectExchangeParametersError',
  ],
  InvalidFanoutExchangeParametersError: [
    400,
    'InvalidFanoutExchangeParametersError',
  ],
  InvalidNamespaceError: [400, 'InvalidNamespaceError'],
  InvalidQueueParametersError: [400, 'InvalidQueueParametersError'],
  InvalidRateLimitError: [429, 'InvalidRateLimitError'],
  InvalidRateLimitIntervalError: [429, 'InvalidRateLimitIntervalError'],
  InvalidSchedulingParametersError: [400, 'InvalidSchedulingParametersError'],
  InvalidTopicExchangeParamsError: [400, 'InvalidTopicExchangeParamsError'],
  MessageAlreadyExistsError: [409, 'MessageAlreadyExistsError'],
  MessageDestinationQueueAlreadySetError: [
    500,
    'MessageDestinationQueueAlreadySetError',
  ],
  MessageDestinationQueueRequiredError: [
    400,
    'MessageDestinationQueueRequiredError',
  ],
  MessageError: [500, 'MessageError'],
  MessageExchangeError: [500, 'MessageExchangeError'],
  MessageExchangeRequiredError: [400, 'MessageExchangeRequiredError'],
  MessageHandlerAlreadyExistsError: [409, 'MessageHandlerAlreadyExistsError'],
  MessageHandlerError: [500, 'MessageHandlerError'],
  MessageHandlerFileError: [500, 'MessageHandlerFileError'],
  MessageHandlerFilenameExtensionError: [
    500,
    'MessageHandlerFilenameExtensionError',
  ],
  MessageManagerError: [500, 'MessageManagerError'],
  MessageNotFoundError: [404, 'MessageNotFoundError'],
  MessageNotRequeuableError: [500, 'MessageNotRequeuableError'],
  MessagePriorityRequiredError: [400, 'MessagePriorityRequiredError'],
  MessagePropertyError: [500, 'MessagePropertyError'],
  NamespaceManagerError: [500, 'NamespaceManagerError'],
  NamespaceNotFoundError: [404, 'NamespaceNotFoundError'],
  NoMatchedQueueForExchangeError: [500, 'NoMatchedQueueForExchangeError'],
  PriorityQueuingNotEnabledError: [500, 'PriorityQueuingNotEnabledError'],
  ProducerError: [500, 'ProducerError'],
  ProducerNotRunningError: [500, 'ProducerNotRunningError'],
  QueueAlreadyExistsError: [409, 'QueueAlreadyExistsError'],
  QueueDeliveryModelMismatchError: [500, 'QueueDeliveryModelMismatchError'],
  QueueExplorerError: [500, 'QueueExplorerError'],
  QueueHasNoConsumerGroupsError: [500, 'QueueHasNoConsumerGroupsError'],
  QueueManagerActiveConsumersError: [500, 'QueueManagerActiveConsumersError'],
  QueueManagerError: [500, 'QueueManagerError'],
  QueueNotBoundError: [500, 'QueueNotBoundError'],
  QueueNotEmptyError: [409, 'QueueNotEmptyError'],
  QueueNotFoundError: [404, 'QueueNotFoundError'],
  QueueRateLimitError: [429, 'QueueRateLimitError'],
  RedisKeysError: [500, 'RedisKeysError'],
  RedisKeysInvalidKeyError: [400, 'RedisKeysInvalidKeyError'],
  UnknownQueueTypeError: [500, 'UnknownQueueTypeError'],
} as const;

export type TErrors = typeof errors;
