/*
 * Copyright (c)
 * Weyoss <weyoss@protonmail.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

// This file is auto-generated from errors.template.ts by scripts/error-mappings-gen.js
// Do not edit this file directly. Edit the template or the generator instead.

/**
 * The generator replaces the placeholder below with entries like:
 * ErrorName: [400, 'ErrorName'],
 */
export const errors = {
  /* __ERRORS__ */
} as const;

export type TErrors = typeof errors;
