/*
 * Copyright (c)
 * Weyoss <weyoss@outlook.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

// This file is auto-generated from errors.template.ts by scripts/error-mappings-gen.js
// Do not edit this file directly. Edit the template or the generator instead.

/**
 * The generator replaces the placeholder below with entries like:
 * ErrorName: [400, 'ErrorName'],
 */
export const errors = {
  AcknowledgedMessageAuditNotEnabledError: [
    500,
    'AcknowledgedMessageAuditNotEnabledError',
  ],
  BackgroundJobNotFoundError: [404, 'BackgroundJobNotFoundError'],
  BackgroundJobTargetLockedError: [500, 'BackgroundJobTargetLockedError'],
  ConfigurationMessageAuditExpireError: [
    400,
    'ConfigurationMessageAuditExpireError',
  ],
  ConfigurationMessageAuditQueueSizeError: [
    400,
    'ConfigurationMessageAuditQueueSizeError',
  ],
  ConfigurationNamespaceError: [400, 'ConfigurationNamespaceError'],
  ConfigurationUpdateError: [400, 'ConfigurationUpdateError'],
  ConsumerGroupNotEmptyError: [409, 'ConsumerGroupNotEmptyError'],
  ConsumerGroupNotFoundError: [404, 'ConsumerGroupNotFoundError'],
  ConsumerGroupRequiredError: [400, 'ConsumerGroupRequiredError'],
  ConsumerGroupsNotSupportedError: [501, 'ConsumerGroupsNotSupportedError'],
  ConsumerSetMismatchError: [500, 'ConsumerSetMismatchError'],
  DeadLetteredMessageAuditNotEnabledError: [
    500,
    'DeadLetteredMessageAuditNotEnabledError',
  ],
  ExchangeAlreadyExistsError: [409, 'ExchangeAlreadyExistsError'],
  ExchangeHasBoundQueuesError: [500, 'ExchangeHasBoundQueuesError'],
  ExchangeNotFoundError: [404, 'ExchangeNotFoundError'],
  ExchangeQueuePolicyMismatchError: [500, 'ExchangeQueuePolicyMismatchError'],
  ExchangeRequiredError: [400, 'ExchangeRequiredError'],
  ExchangeTypeMismatchError: [500, 'ExchangeTypeMismatchError'],
  InvalidConfigurationError: [400, 'InvalidConfigurationError'],
  InvalidConsumerGroupIdError: [400, 'InvalidConsumerGroupIdError'],
  InvalidCronExpressionError: [400, 'InvalidCronExpressionError'],
  InvalidDirectExchangeParametersError: [
    400,
    'InvalidDirectExchangeParametersError',
  ],
  InvalidExchangeParametersError: [400, 'InvalidExchangeParametersError'],
  InvalidFanoutExchangeParametersError: [
    400,
    'InvalidFanoutExchangeParametersError',
  ],
  InvalidNamespaceError: [400, 'InvalidNamespaceError'],
  InvalidPurgeQueueJobIdError: [400, 'InvalidPurgeQueueJobIdError'],
  InvalidQueueParametersError: [400, 'InvalidQueueParametersError'],
  InvalidQueueTypeError: [400, 'InvalidQueueTypeError'],
  InvalidRateLimitIntervalError: [429, 'InvalidRateLimitIntervalError'],
  InvalidRateLimitValueError: [429, 'InvalidRateLimitValueError'],
  InvalidRedisKeyError: [400, 'InvalidRedisKeyError'],
  InvalidSchedulingParametersError: [400, 'InvalidSchedulingParametersError'],
  InvalidTopicBindingPatternError: [400, 'InvalidTopicBindingPatternError'],
  InvalidTopicExchangeParamsError: [400, 'InvalidTopicExchangeParamsError'],
  MessageAlreadyExistsError: [409, 'MessageAlreadyExistsError'],
  MessageDestinationQueueAlreadySetError: [
    500,
    'MessageDestinationQueueAlreadySetError',
  ],
  MessageDestinationQueueRequiredError: [
    400,
    'MessageDestinationQueueRequiredError',
  ],
  MessageExchangeRequiredError: [400, 'MessageExchangeRequiredError'],
  MessageHandlerAlreadyExistsError: [409, 'MessageHandlerAlreadyExistsError'],
  MessageHandlerFileError: [500, 'MessageHandlerFileError'],
  MessageHandlerFilenameExtensionError: [
    500,
    'MessageHandlerFilenameExtensionError',
  ],
  MessageNotFoundError: [404, 'MessageNotFoundError'],
  MessageNotRequeuableError: [500, 'MessageNotRequeuableError'],
  MessagePriorityRequiredError: [400, 'MessagePriorityRequiredError'],
  MessagePropertyInvalidValueError: [400, 'MessagePropertyInvalidValueError'],
  NamespaceMismatchError: [500, 'NamespaceMismatchError'],
  NamespaceNotFoundError: [404, 'NamespaceNotFoundError'],
  NoMatchedQueuesForMessageExchangeError: [
    500,
    'NoMatchedQueuesForMessageExchangeError',
  ],
  PriorityQueuingNotEnabledError: [500, 'PriorityQueuingNotEnabledError'],
  ProducerNotRunningError: [500, 'ProducerNotRunningError'],
  QueueAlreadyBound: [500, 'QueueAlreadyBound'],
  QueueAlreadyExistsError: [409, 'QueueAlreadyExistsError'],
  QueueDeliveryModelMismatchError: [500, 'QueueDeliveryModelMismatchError'],
  QueueHasBoundExchangesError: [500, 'QueueHasBoundExchangesError'],
  QueueHasNoConsumerGroupsError: [500, 'QueueHasNoConsumerGroupsError'],
  QueueManagerActiveConsumersError: [500, 'QueueManagerActiveConsumersError'],
  QueueNotBoundError: [500, 'QueueNotBoundError'],
  QueueNotEmptyError: [409, 'QueueNotEmptyError'],
  QueueNotFoundError: [404, 'QueueNotFoundError'],
  RequeueMessageScriptError: [500, 'RequeueMessageScriptError'],
  RoutingKeyRequiredError: [400, 'RoutingKeyRequiredError'],
  ScriptResultMismatchError: [500, 'ScriptResultMismatchError'],
  UnexpectedScriptReplyError: [500, 'UnexpectedScriptReplyError'],
} as const;

export type TErrors = typeof errors;
