/*
 * Copyright (c)
 * Weyoss <weyoss@outlook.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

// This file is auto-generated from errors.template.ts by scripts/error-mappings-gen.js
// Do not edit this file directly. Edit the template or the generator instead.

/**
 * The generator replaces the placeholder below with entries like:
 * ErrorName: [400, 'ErrorName'],
 */
export const errors = {
  AcknowledgmentAuditDisabledError: [412, 'AcknowledgmentAuditDisabledError'],
  BackgroundJobAlreadyExistsError: [409, 'BackgroundJobAlreadyExistsError'],
  BackgroundJobCanceledError: [403, 'BackgroundJobCanceledError'],
  BackgroundJobNotCancellableError: [403, 'BackgroundJobNotCancellableError'],
  BackgroundJobNotCompletableError: [403, 'BackgroundJobNotCompletableError'],
  BackgroundJobNotFailableError: [403, 'BackgroundJobNotFailableError'],
  BackgroundJobNotFoundError: [400, 'BackgroundJobNotFoundError'],
  BackgroundJobNotStartableError: [403, 'BackgroundJobNotStartableError'],
  BackgroundJobTargetLockedError: [403, 'BackgroundJobTargetLockedError'],
  BackgroundJobWorkerNotFoundError: [400, 'BackgroundJobWorkerNotFoundError'],
  ConfigurationMessageAuditExpireError: [
    422,
    'ConfigurationMessageAuditExpireError',
  ],
  ConfigurationNamespaceError: [422, 'ConfigurationNamespaceError'],
  ConfigurationUpdateError: [422, 'ConfigurationUpdateError'],
  ConsumerGroupHasActiveConsumersError: [
    409,
    'ConsumerGroupHasActiveConsumersError',
  ],
  ConsumerGroupNotEmptyError: [412, 'ConsumerGroupNotEmptyError'],
  ConsumerGroupNotFoundError: [400, 'ConsumerGroupNotFoundError'],
  ConsumerGroupRequiredError: [412, 'ConsumerGroupRequiredError'],
  ConsumerGroupsNotSupportedError: [422, 'ConsumerGroupsNotSupportedError'],
  ConsumerSetMismatchError: [403, 'ConsumerSetMismatchError'],
  DeadLetterAuditDisabledError: [412, 'DeadLetterAuditDisabledError'],
  ExchangeAlreadyExistsError: [409, 'ExchangeAlreadyExistsError'],
  ExchangeHasBoundQueuesError: [409, 'ExchangeHasBoundQueuesError'],
  ExchangeNotFoundError: [400, 'ExchangeNotFoundError'],
  ExchangeQueuePolicyMismatchError: [422, 'ExchangeQueuePolicyMismatchError'],
  ExchangeRequiredError: [400, 'ExchangeRequiredError'],
  ExchangeTypeMismatchError: [422, 'ExchangeTypeMismatchError'],
  InvalidConfigurationError: [400, 'InvalidConfigurationError'],
  InvalidConsumerGroupIdError: [400, 'InvalidConsumerGroupIdError'],
  InvalidCronExpressionError: [400, 'InvalidCronExpressionError'],
  InvalidDirectExchangeParametersError: [
    400,
    'InvalidDirectExchangeParametersError',
  ],
  InvalidExchangeParametersError: [400, 'InvalidExchangeParametersError'],
  InvalidExchangeRoutingKeyError: [400, 'InvalidExchangeRoutingKeyError'],
  InvalidFanoutExchangeParametersError: [
    400,
    'InvalidFanoutExchangeParametersError',
  ],
  InvalidMessageAuditHistorySizeError: [
    400,
    'InvalidMessageAuditHistorySizeError',
  ],
  InvalidMessageAuditQueueSizeError: [400, 'InvalidMessageAuditQueueSizeError'],
  InvalidMessageHandlerSignatureError: [
    400,
    'InvalidMessageHandlerSignatureError',
  ],
  InvalidMessageHandlerTypeError: [400, 'InvalidMessageHandlerTypeError'],
  InvalidNamespaceError: [400, 'InvalidNamespaceError'],
  InvalidPurgeQueueJobIdError: [400, 'InvalidPurgeQueueJobIdError'],
  InvalidQueueLockIdError: [400, 'InvalidQueueLockIdError'],
  InvalidQueueParametersError: [400, 'InvalidQueueParametersError'],
  InvalidQueueStateError: [400, 'InvalidQueueStateError'],
  InvalidQueueTypeError: [422, 'InvalidQueueTypeError'],
  InvalidRateLimitIntervalError: [400, 'InvalidRateLimitIntervalError'],
  InvalidRateLimitValueError: [400, 'InvalidRateLimitValueError'],
  InvalidRedisKeyError: [400, 'InvalidRedisKeyError'],
  InvalidSchedulingParametersError: [400, 'InvalidSchedulingParametersError'],
  InvalidTopicBindingPatternError: [400, 'InvalidTopicBindingPatternError'],
  InvalidTopicExchangeParamsError: [400, 'InvalidTopicExchangeParamsError'],
  MessageAlreadyExistsError: [409, 'MessageAlreadyExistsError'],
  MessageDestinationQueueAlreadySetError: [
    412,
    'MessageDestinationQueueAlreadySetError',
  ],
  MessageDestinationQueueRequiredError: [
    412,
    'MessageDestinationQueueRequiredError',
  ],
  MessageExchangeRequiredError: [400, 'MessageExchangeRequiredError'],
  MessageHandlerAlreadyExistsError: [409, 'MessageHandlerAlreadyExistsError'],
  MessageHandlerFileError: [400, 'MessageHandlerFileError'],
  MessageHandlerFilenameExtensionError: [
    400,
    'MessageHandlerFilenameExtensionError',
  ],
  MessageNotFoundError: [400, 'MessageNotFoundError'],
  MessageNotRequeuableError: [412, 'MessageNotRequeuableError'],
  MessagePriorityRequiredError: [400, 'MessagePriorityRequiredError'],
  MessagePropertyInvalidValueError: [400, 'MessagePropertyInvalidValueError'],
  NamespaceMismatchError: [403, 'NamespaceMismatchError'],
  NamespaceNotFoundError: [400, 'NamespaceNotFoundError'],
  NoMatchingQueuesError: [422, 'NoMatchingQueuesError'],
  PriorityQueuingNotEnabledError: [412, 'PriorityQueuingNotEnabledError'],
  ProcessingQueueNotEmptyError: [412, 'ProcessingQueueNotEmptyError'],
  ProducerNotRunningError: [400, 'ProducerNotRunningError'],
  QueueAlreadyBeingPurgedError: [409, 'QueueAlreadyBeingPurgedError'],
  QueueAlreadyBound: [400, 'QueueAlreadyBound'],
  QueueAlreadyExistsError: [409, 'QueueAlreadyExistsError'],
  QueueHasActiveConsumersError: [412, 'QueueHasActiveConsumersError'],
  QueueHasBoundExchangesError: [409, 'QueueHasBoundExchangesError'],
  QueueHasNoConsumerGroupsError: [400, 'QueueHasNoConsumerGroupsError'],
  QueueLockedError: [403, 'QueueLockedError'],
  QueueLockOwnerMismatchError: [403, 'QueueLockOwnerMismatchError'],
  QueueNotActiveError: [403, 'QueueNotActiveError'],
  QueueNotBoundError: [412, 'QueueNotBoundError'],
  QueueNotEmptyError: [412, 'QueueNotEmptyError'],
  QueueNotFoundError: [400, 'QueueNotFoundError'],
  QueueNotLockedError: [403, 'QueueNotLockedError'],
  QueueOperationForbiddenError: [403, 'QueueOperationForbiddenError'],
  QueuePausedError: [403, 'QueuePausedError'],
  QueueStateTransitionError: [422, 'QueueStateTransitionError'],
  QueueStoppedError: [403, 'QueueStoppedError'],
  RequeueMessageScriptError: [422, 'RequeueMessageScriptError'],
  RoutingKeyRequiredError: [400, 'RoutingKeyRequiredError'],
  ScriptResultMismatchError: [422, 'ScriptResultMismatchError'],
  UnacknowledgmentHistoryDisabledError: [
    412,
    'UnacknowledgmentHistoryDisabledError',
  ],
  UnexpectedScriptReplyError: [422, 'UnexpectedScriptReplyError'],
} as const;

export type TErrors = typeof errors;
