/*
 * Copyright (c)
 * Weyoss <weyoss@outlook.com>
 * https://github.com/weyoss
 *
 * This source code is licensed under the MIT license found in the LICENSE file
 * in the root directory of this source tree.
 */

import { IRedisSMQParsedConfig } from '../config-manager/config.js';
import {
  EMessageDeadLetterCause,
  EMessageUnacknowledgementCause,
} from '../message/index.js';
import {
  IQueueParams,
  IQueueParsedParams,
  IQueueProperties,
} from '../queue-manager/queue.js';
import { IQueueStateTransition } from '../queue-state-manager/index.js';

/**
 * Configuration events.
 *
 * Emitted when the runtime configuration changes. The event carries the
 * fully-parsed configuration and the new version number.
 *
 * Only one event in this category today.
 */
export type TConfigurationEvent = {
  /**
   * The configuration was updated.
   *
   * Fires in the process that performed the update, and in every other
   * process connected to the same Redis instance via the configuration
   * sync mechanism. A subscriber sees the event once per update per
   * process, after the version number has been incremented.
   *
   * @param config - The new fully-parsed configuration.
   * @param version - The new version number. Monotonically increasing;
   *   a subscriber can compare against the previously seen version to
   *   ignore out-of-order deliveries.
   */
  'configuration.updated': (
    config: IRedisSMQParsedConfig,
    version: number,
  ) => void;
};

/**
 * Consumer events.
 *
 * Emitted by `Consumer` instances and by the internal message handlers
 * they own. Lifecycle events (`up`, `down`, `goingUp`, `goingDown`) are
 * one per consumer instance. Message-outcome events are one per message
 * per consumer.
 *
 * The `queue` payload on message events is an `IQueueParsedParams` — it
 * carries the effective consumer group ID for PUB/SUB queues, which may
 * be an ephemeral `cid-<consumerId>` generated by the library.
 */
export type TConsumerEvent = {
  /**
   * The consumer has finished starting up.
   *
   * Fires after the consumer's Redis connection is established, its
   * heartbeat is running, and its message handlers are subscribed.
   */
  'consumer.up': (consumerId: string) => void;

  /**
   * The consumer has started shutting down.
   *
   * Fires at the beginning of `shutdown()`, before any resources are
   * released. Subscribers who need to observe the consumer while it is
   * still running should use this event; by the time `consumer.down`
   * fires, the consumer is fully stopped.
   */
  'consumer.goingDown': (consumerId: string) => void;

  /**
   * The consumer has finished shutting down.
   *
   * Fires after all resources are released — message handlers stopped,
   * heartbeat removed, Redis connection returned to the pool.
   */
  'consumer.down': (consumerId: string) => void;

  /**
   * The consumer has started starting up.
   *
   * Fires at the beginning of `run()`, before any resources are
   * acquired. Useful for instrumentation that measures startup duration.
   */
  'consumer.goingUp': (consumerId: string) => void;

  /**
   * A message was handed to a consumer handler.
   *
   * Fires when the message's checkout script succeeds — the message has
   * been moved from the pending list to the consumer's processing queue
   * and the handler is about to be invoked. Does not fire for messages
   * that the checkout script rejects (queue stopped, locked, invalid
   * state).
   *
   * Emitted before the handler runs. A subscriber that needs the
   * post-handler outcome should listen for `consumer.messageAcknowledged`
   * or `consumer.messageUnacknowledged` instead.
   */
  'consumer.messageReceived': (
    messageId: string,
    queue: IQueueParsedParams,
    consumerId: string,
  ) => void;

  /**
   * A message was successfully processed and acknowledged.
   *
   * Fires after the handler has completed successfully and the
   * acknowledgement has been accepted by the acknowledger (which may
   * batch internally — the event fires when the message enters the
   * batch, not when the batch flushes).
   */
  'consumer.messageAcknowledged': (
    messageId: string,
    queue: IQueueParsedParams,
    consumerId: string,
  ) => void;

  /**
   * A message was unacknowledged.
   *
   * Fires for any failed processing — a handler that threw, a
   * consumption timeout, a message that expired before processing, a
   * consumer that went offline mid-processing. The `unacknowledgmentCause`
   * field distinguishes the cases.
   *
   * The unacknowledgement pipeline's resolution — requeue, delay, or
   * dead-letter — is decided by the message's retry policy. A subscriber
   * who wants to know the resolution listens for the corresponding
   * follow-up event (`consumer.messageRequeued`,
   * `consumer.messageDelayed`, or `consumer.messageDeadLettered`) or
   * inspects the message's state.
   */
  'consumer.messageUnacknowledged': (
    messageId: string,
    queue: IQueueParsedParams,
    consumerId: string,
    unacknowledgmentCause: EMessageUnacknowledgementCause,
  ) => void;

  /**
   * A message was unacknowledged and moved to the dead-letter list.
   *
   * Fires in addition to `consumer.messageUnacknowledged`, with a more
   * specific payload. A subscriber who only cares about failures that
   * exhausted their retry policy subscribes to this event alone.
   *
   * The `deadLetterCause` distinguishes TTL expiry, retry-threshold
   * exhaustion, and periodic-message termination.
   */
  'consumer.messageDeadLettered': (
    messageId: string,
    queue: IQueueParsedParams,
    consumerId: string,
    deadLetterCause: EMessageDeadLetterCause,
  ) => void;

  /**
   * A message was unacknowledged and requeued for immediate reprocessing.
   *
   * Fires in addition to `consumer.messageUnacknowledged`. The requeued
   * message is placed in the pending list; its ID is unchanged. A
   * subsequent delivery attempt follows the same path as the original
   * one.
   */
  'consumer.messageRequeued': (
    messageId: string,
    queue: IQueueParsedParams,
    consumerId: string,
  ) => void;

  /**
   * A message was unacknowledged and delayed for a scheduled retry.
   *
   * Fires in addition to `consumer.messageUnacknowledged`. The message
   * is placed in the delayed set with a score of `now + retryDelay`. A
   * scheduled worker will move it back to the pending list when the
   * delay elapses.
   */
  'consumer.messageDelayed': (
    messageId: string,
    queue: IQueueParsedParams,
    consumerId: string,
  ) => void;
};

/**
 * Producer events.
 *
 * Emitted by `Producer` instances. Lifecycle events are one per producer;
 * `producer.messagePublished` fires once per destination queue a message
 * was produced to (and, for PUB/SUB queues, once per consumer group).
 *
 * The producer's internal `PubSubTargetResolver` does not emit a public
 * event when it errors; a resolver failure tears the producer down and
 * is observable via the `producer.down` event plus the logs. A caller
 * that wants to react to resolver failures should watch `producer.down`
 * and reconnect.
 */
export type TProducerEvent = {
  /**
   * The producer has finished starting up.
   *
   * Fires after the producer's Redis connection is established and its
   * `PubSubTargetResolver` cache is loaded. Publishing is possible only
   * after this event fires.
   */
  'producer.up': (producerId: string) => void;

  /**
   * The producer has started shutting down.
   *
   * Fires at the beginning of `shutdown()`.
   */
  'producer.goingDown': (producerId: string) => void;

  /**
   * The producer has finished shutting down.
   */
  'producer.down': (producerId: string) => void;

  /**
   * The producer has started starting up.
   */
  'producer.goingUp': (producerId: string) => void;

  /**
   * A message was published to a destination queue.
   *
   * Fires once per destination queue, and once per consumer group for
   * PUB/SUB destinations. A fan-out to N queues with M groups produces
   * up to N × M events, each with a distinct `messageId`.
   *
   * Does not fire for scheduled messages. A message published with
   * scheduling parameters is placed in the scheduled set and does not
   * reach a pending queue until the schedule fires; the corresponding
   * `producer.messagePublished` event fires at that later point, from
   * the scheduled-message worker rather than from the producer.
   */
  'producer.messagePublished': (
    messageId: string,
    queue: IQueueParsedParams,
    producerId: string,
  ) => void;
};

/**
 * Queue events.
 *
 * Emitted by the queue-management layer — `QueueManager`,
 * `NamespaceManager`, `ConsumerGroups`, `QueueStateManager` — and by any
 * operation that changes a queue's state or membership.
 *
 * The queue payload here is `IQueueParams` (name + namespace), not
 * `IQueueParsedParams`. Queue-level events describe the queue as a
 * whole; the consumer-group dimension is present on consumer message
 * events, not on queue events. A subscriber who needs the group ID in
 * the context of a queue event correlates by queue name.
 */
export type TQueueEvent = {
  /**
   * A consumer group was created on a queue.
   *
   * Fires once per successful creation. A no-op call (the group already
   * existed) does not fire the event — the return value of
   * `IConsumerGroups.saveConsumerGroup` is the authoritative signal for
   * "created" vs. "already existed".
   */
  'queue.consumerGroupCreated': (queue: IQueueParams, groupId: string) => void;

  /**
   * A consumer group was deleted from a queue.
   *
   * Fires once per successful deletion. The deletion's preconditions
   * (no active consumers, empty pending queue) are enforced before the
   * event fires; a caller that receives this event can assume the group
   * is fully gone.
   */
  'queue.consumerGroupDeleted': (queue: IQueueParams, groupId: string) => void;

  /**
   * A queue was created.
   *
   * Fires once per successful creation. A no-op call (the queue already
   * existed) does not fire the event; the corresponding
   * `QueueAlreadyExistsError` is the signal for a duplicate creation
   * attempt.
   *
   * The payload carries the queue's initial properties. A subscriber
   * that needs the queue's current properties (which may have changed
   * since creation) reads them via `IQueueManager.getProperties`.
   */
  'queue.queueCreated': (
    queue: IQueueParams,
    properties: IQueueProperties,
  ) => void;

  /**
   * A queue was deleted.
   *
   * Fires once per successful deletion. All of the queue's data
   * structures have been removed by the time this event fires.
   */
  'queue.queueDeleted': (queue: IQueueParams) => void;

  /**
   * A queue's operational state changed.
   *
   * Fires whenever the queue moves between `ACTIVE`, `PAUSED`,
   * `STOPPED`, and `LOCKED`. The payload carries the full transition
   * record — the previous state, the new state, the reason, the
   * timestamp, and any lock metadata.
   *
   * This is the same event the library uses internally for its own
   * coordination (the consumer's `QueueStateChangeHandler` subscribes
   * to the internal copy). The public event is the same payload; a
   * subscriber to the public bus sees it alongside the internal
   * subscribers.
   */
  'queue.stateChanged': (
    queue: IQueueParams,
    transition: IQueueStateTransition,
  ) => void;
};

/**
 * The union of every event the library can emit on the public event bus.
 *
 * Subscribers use this type to constrain their event name and payload:
 *
 *   eventBus.on('queue.queueCreated', (queue, properties) => {
 *     // `queue` is IQueueParams
 *     // `properties` is IQueueProperties
 *   });
 *
 * The intersection of the four category maps means a subscription is
 * valid for any event in any category. The compiler enforces that the
 * listener's parameters match the event's payload shape.
 *
 * The type is used throughout the event bus, the multiplexer's routing
 * table, and every `eventPublisher` module that forwards a component's
 * local events to the public bus.
 */
export type TRedisSMQEvent = TConfigurationEvent &
  TConsumerEvent &
  TProducerEvent &
  TQueueEvent;
