'use strict';

module.exports = {
    BOOTSTRAP_REDIS_CLIENT: 'bootstrap.redis_client',
    BOOTSTRAP_SYSTEM_QUEUES: 'bootstrap.system_queues',
    BOOTSTRAP_SUCCESS: 'bootstrap.success',
    GOING_UP: 'going_up',
    UP: 'up',
    GOING_DOWN: 'going_down',
    DOWN: 'down',
    ERROR: 'error',
    IDLE: 'idle',
    HEARTBEAT_UP: 'heartbeat.up',
    HEARTBEAT_DOWN: 'heartbeat.down',
    GC_UP: 'gc.up',
    GC_DOWN: 'gc.down',
    SCHEDULER_UP: 'scheduler.up',
    SCHEDULER_DOWN: 'scheduler.down',
    STATS_UP: 'stats.up',
    STATS_DOWN: 'stats.down',
    MESSAGE_PRODUCED: 'message.produced',
    MESSAGE_NEXT: 'message.next',
    MESSAGE_RECEIVED: 'message.received',
    MESSAGE_ACKNOWLEDGED: 'message.acknowledged',
    MESSAGE_UNACKNOWLEDGED: 'message.unacknowledged',
    MESSAGE_CONSUME_TIMEOUT: 'message.consume_timeout',
    MESSAGE_EXPIRED: 'message.expired',
    MESSAGE_REQUEUED: 'message.requeued',
    MESSAGE_DELAYED: 'message.delayed',
    MESSAGE_DEAD_LETTER: 'message.moved_to_dlq',
    MESSAGE_DESTROYED: 'message.destroyed'
};
